import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Parkinsans, Libre_Franklin } from "next/font/google";
import "./globals.css";
import Navbar from "../components/usable-components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const libre = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100","300","400","600","900"],
  style: ["normal","italic"],
  variable: "--font-body",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const parkinsans = Parkinsans({
  subsets: ["latin"],
  weight: ["300","400","500","600","700","800"],
  style: ["normal"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre.variable} ${parkinsans.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
